In [2]:
import numpy as np

# 1. 배열 생성

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

## 1.1. 자료형 지정

In [34]:
np.array([1.2, 2.1, -1.6, 4.45], dtype='f')

array([ 1.2 ,  2.1 , -1.6 ,  4.45], dtype=float32)

## 1.2. 영벡터 생성

In [36]:
np.zeros(3, dtype='i')

array([0, 0, 0], dtype=int32)

In [37]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

## 1.3. 원소가 1인 벡터 생성

In [38]:
np.ones((2, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## 1.4. 다른 배열을 이용한 벡터 생성

In [42]:
a = np.array([[1, 2,], [3, 4], [5, 6]])
print(a)
print(a.shape)
b = np.zeros_like(a, dtype='f')
# b = np.ones_like(a, dtype='f')
print()
print(b)
print(b.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


## 1.5. 초기화 없이 배열 생성
### @메모리에 있는 값을 바탕으로 배열 요소값이 지정됨

In [45]:
a = np.empty((10, 3))
print(a)

[[1.41158355e-311 9.58487353e-322 0.00000000e+000]
 [0.00000000e+000 6.95293141e-310 5.02034658e+175]
 [1.27010965e-075 2.57751692e-056 4.16150492e-061]
 [6.12673096e-062 1.47763641e+248 1.16096346e-028]
 [7.69165785e+218 1.35617292e+248 1.10208290e-046]
 [5.64373615e-038 1.40415688e+165 2.89818752e-057]
 [4.26050046e-096 6.32299154e+233 6.48224638e+170]
 [5.22411352e+257 5.74020278e+180 8.37174974e-144]
 [1.41529402e+161 9.16651763e-072 4.52660428e+097]
 [1.24716443e-047 3.58569463e+126 2.12201162e-314]]


## 1.6. Arange 사용

In [46]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# np.arange(시작, 끝, 공차)
np.arange(3, 20, 4)

array([ 3,  7, 11, 15, 19])

# 2. 차원 확인

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print(np.ndim(a))

(2, 3)
2


In [31]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[2, 4, 6], [-1, 0, 0]]])
print(a)
print(a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 2  4  6]
  [-1  0  0]]]
(2, 2, 3)


In [5]:
a = np.array([[[1, 2, 3]], [[-1, 0, 0]]])
print(a)
print(a.shape)
print(np.ndim(a))

[[[ 1  2  3]]

 [[-1  0  0]]]
(2, 1, 3)
3


# 3. 차원 변경

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [13]:
print(a.reshape([2, 3]))

[[1 2 3]
 [4 5 6]]


In [14]:
print(a.reshape([2, -1]))

[[1 2 3]
 [4 5 6]]


In [15]:
print(a.reshape([-1, 2]))

[[1 2]
 [3 4]
 [5 6]]


In [20]:
print(a.reshape([2, 3, 1]))

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


## 3.1. 전치

In [50]:
a = np.array([[1, 2, 3,], [4, 5, 6]])
print(a)
print(a.shape)
print()

b = a.T
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


## 3.2. 차원축 추가

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)
print()

a = np.expand_dims(a, axis=0)
print(a.shape)

(2, 3)

(1, 2, 3)


# 4. 자료형 변경

In [57]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.astype('float32'))

[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


# 5. 배열 계산

## 5.1. Elementwise 계산

In [59]:
a = np.array([[1, 2, 3], [4, 5, 6]]).astype('float32')
print(a)
print(a/2)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
b = a >= 4
print(b)
print(b.astype(np.int))

[1 2 3 4 5 6]
[False False False  True  True  True]
[0 0 0 1 1 1]


## 5.2. 행렬 곱

In [8]:
a = np.array([[1, 0], [2, 2]])
print(a.shape)

b = np.array([[2, 2], [3, 0]])
print(b.shape)

print(np.dot(a, b))

(2, 2)
(2, 2)
[[ 2  2]
 [10  4]]


In [9]:
a = np.array(
    [[1, 1, 2],
     [0, 2, 0]])
print(a.shape)

b = np.array(
    [[1, 2],
     [0, 3],
     [1, 1]])
print(b.shape)

print(np.dot(a, b))

(2, 3)
(3, 2)
[[3 7]
 [0 6]]


# 6. hstack

In [3]:
a = np.array([1, 1, [2, 2, -1], [3, 0], 6])
print(a)
b = np.hstack(a)
print(b)

[1 1 list([2, 2, -1]) list([3, 0]) 6]
[ 1  1  2  2 -1  3  0  6]


In [7]:
a = np.array([[1, 1, [2, 2, -1], [3, 0], 6], [12, 12, [21, 21, -11], [30, 0], 16]])
print(a)
b = np.hstack(a)
print(b)

[[1 1 list([2, 2, -1]) list([3, 0]) 6]
 [12 12 list([21, 21, -11]) list([30, 0]) 16]]
[1 1 list([2, 2, -1]) list([3, 0]) 6 12 12 list([21, 21, -11])
 list([30, 0]) 16]


In [11]:
tmp = list()
for i in a:
    tmp.append(np.hstack(i))

tmp1 = np.vstack(tmp)
print(tmp1)

[[  1   1   2   2  -1   3   0   6]
 [ 12  12  21  21 -11  30   0  16]]
