In [1]:
import numpy as np

# argmax, argmin

argmax 함수는 넘파이 배열에서 최댓값인 요소의 인덱스를 반환한다.<br>
argmin 함수는 넘파이 배열에서 최솟값인 요소의 인덱스를 반환한다.

In [11]:
a = np.array([0.35, 1.67, 0.4123, 0.1296, 1.2395])
print(np.argmax(a))
print(a.argmax())

1
1


In [18]:
b = np.array([
    [1, 2, 3],
    [0, 2, 1],
    [4, 2, 0],
    [4, 5, 3]])
print(np.argmin(b))
print(np.argmin(b, axis=1))

3
[0 0 2 2]


# where

where 함수는 넘파이 배열의 요소 중 조건에 맞는 요소의 인덱스를 반환한다.

In [23]:
a = np.array([0, 1, 2, 0, 3, 3, 5])
print(np.where(a <= 1))

(array([0, 1, 3], dtype=int64),)


조건에 맞거나 맞지 않는 값을 다른 값으로 변환할 수도 있다.<br>
np.where(변환 조건, true 일 때 값, false 일 때 값)

In [25]:
print(np.where(a >= 2, 99, a))

[ 0  1 99  0 99 99 99]
